export interface FilmEntry {
  title: string
  year: string
  rating: string
  posterDataUrl: string
}

export interface CardOptions {
  films: FilmEntry[]
  username: string
  showTitle: boolean
  showYear: boolean   // only relevant when showTitle is true
  showRating: boolean
  showDate: boolean
}

const CARD_WIDTH   = 1200
const CARD_HEIGHT  = 560
const POSTER_W     = 200
const POSTER_H     = 300
const POSTER_GAP   = 20
const POSTER_TOP   = 80
const HEADER_H     = 60
const FOOTER_Y     = 496

// Derived: 4 posters + 3 gaps = 860px; center them
const POSTERS_TOTAL_W = 4 * POSTER_W + 3 * POSTER_GAP
const POSTER_LEFT     = (CARD_WIDTH - POSTERS_TOTAL_W) / 2

const BG_COLOR      = '#1a1a1a'
const TEXT_COLOR    = '#ffffff'
const SUBTEXT_COLOR = '#99aabb'
const DIM_COLOR     = '#666677'

// Letterboxd brand dots
const DOTS = [
  { color: '#FF8000' }, // orange
  { color: '#00C030' }, // green
  { color: '#40BCF4' }, // teal
]
const DOT_R    = 9
const DOT_GAP  = 4

function drawLogo(ctx: CanvasRenderingContext2D, x: number, y: number) {
  // Three colored dots
  let cx = x + DOT_R
  for (const { color } of DOTS) {
    ctx.beginPath()
    ctx.arc(cx, y, DOT_R, 0, Math.PI * 2)
    ctx.fillStyle = color
    ctx.fill()
    cx += DOT_R * 2 + DOT_GAP
  }
  // "Letterboxd" wordmark text
  ctx.fillStyle = TEXT_COLOR
  ctx.font = 'bold 18px sans-serif'
  ctx.textAlign = 'left'
  ctx.textBaseline = 'middle'
  ctx.fillText('Letterboxd', cx + 4, y)
}

function truncate(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text
  let truncated = text
  while (truncated.length > 0 && ctx.measureText(truncated + '…').width > maxWidth) {
    truncated = truncated.slice(0, -1)
  }
  return truncated + '…'
}

export async function renderCard(options: CardOptions): Promise<Blob> {
  const { films, username, showTitle, showYear, showRating, showDate } = options

  const canvas = document.createElement('canvas')
  canvas.width  = CARD_WIDTH
  canvas.height = CARD_HEIGHT
  const ctx = canvas.getContext('2d')!

  // Background
  ctx.fillStyle = BG_COLOR
  ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT)

  // ── Header ──────────────────────────────────────────────
  const headerMidY = HEADER_H / 2

  // Logo (left)
  drawLogo(ctx, 40, headerMidY)

  // Date (right, if enabled)
  if (showDate) {
    const dateStr = new Date().toLocaleDateString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
    })
    ctx.fillStyle = SUBTEXT_COLOR
    ctx.font = '15px sans-serif'
    ctx.textAlign = 'right'
    ctx.textBaseline = 'middle'
    ctx.fillText(dateStr, CARD_WIDTH - 40, headerMidY)
  }

  // ── Posters ──────────────────────────────────────────────
  for (let i = 0; i < Math.min(films.length, 4); i++) {
    const film = films[i]
    const x = POSTER_LEFT + i * (POSTER_W + POSTER_GAP)

    // Poster image
    try {
      const img = await loadImage(film.posterDataUrl)
      ctx.drawImage(img, x, POSTER_TOP, POSTER_W, POSTER_H)
    } catch {
      // Fallback: grey rectangle with film index
      ctx.fillStyle = '#333344'
      ctx.fillRect(x, POSTER_TOP, POSTER_W, POSTER_H)
    }

    // Title
    if (showTitle) {
      const displayTitle = showYear && film.year
        ? `${film.title} (${film.year})`
        : film.title
      ctx.fillStyle = TEXT_COLOR
      ctx.font = '14px sans-serif'
      ctx.textAlign = 'left'
      ctx.textBaseline = 'top'
      ctx.fillText(truncate(ctx, displayTitle, POSTER_W), x, POSTER_TOP + POSTER_H + 10)
    }

    // Rating
    if (showRating && film.rating) {
      ctx.fillStyle = '#FFB020'
      ctx.font = '14px sans-serif'
      ctx.textAlign = 'left'
      ctx.textBaseline = 'top'
      const ratingY = POSTER_TOP + POSTER_H + (showTitle ? 30 : 10)
      ctx.fillText(film.rating, x, ratingY)
    }
  }

  // ── Footer ───────────────────────────────────────────────
  // Username (left)
  ctx.fillStyle = SUBTEXT_COLOR
  ctx.font = '15px sans-serif'
  ctx.textAlign = 'left'
  ctx.textBaseline = 'middle'
  ctx.fillText(`letterboxd.com/${username}`, 40, FOOTER_Y)

  // Attribution (right)
  ctx.fillStyle = DIM_COLOR
  ctx.font = '13px sans-serif'
  ctx.textAlign = 'right'
  ctx.textBaseline = 'middle'
  ctx.fillText('generated by Boxd Card', CARD_WIDTH - 40, FOOTER_Y)

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob) resolve(blob)
        else reject(new Error('canvas.toBlob returned null'))
      },
      'image/png'
    )
  })
}

export async function loadImage(dataUrl: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = reject
    img.src = dataUrl
  })
}
